name: Build Project

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:     
        build:
            runs-on: ubuntu-latest
            name: Build Project
            steps:
              - name: Checkout code
                uses: actions/checkout@v4

              - name: Setup .NET Core
                uses: actions/setup-dotnet@v4
                with:
                  dotnet-version: '8.x'

              - name: Build with .NET
                run: |
                  dotnet restore ./src/Todo.Api.sln
                  dotnet build --no-restore ./src/Todo.Api.sln
                
              - name: Setup Node.js
                uses: actions/setup-node@v4
                with:
                  node-version: '20'

              - name: Install Node.js dependencies
                working-directory: ./src/web
                run: |
                  npm install
                  npm run build